# python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_plus_conf.yaml --api_key "8Qm1rHhRD57Orx4pkbKXT1k1RheU9UPyidVKECLU" --prompt_dir "prompts/gsm8k/standard.txt" --data_path data/gsm8k/test.jsonl --icl_path samples/plans_code_traces/gsm8k/gpt-4-turbo_output.json --data_name "gsm8k" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 8
# python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_conf.yaml --api_key "8Qm1rHhRD57Orx4pkbKXT1k1RheU9UPyidVKECLU" --prompt_dir "prompts/gsm8k/standard.txt" --data_path data/gsm8k/test.jsonl --icl_path samples/plans_code_traces/gsm8k/gpt-4-turbo_output.json --data_name "gsm8k" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 8
# python llmsearch/run_gpt.py --model_config_path llmsearch/models/gpt3_5_conf.yaml --api_key "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" --prompt_dir "prompts/gsm8k/standard.txt" --data_path data/gsm8k/test.jsonl --icl_path samples/plans_code_traces/gsm8k/gpt-4-turbo_output.json --data_name "gsm8k" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 8

# python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_plus_conf.yaml --api_key "8Qm1rHhRD57Orx4pkbKXT1k1RheU9UPyidVKECLU" --prompt_dir "prompts/gsm8k/standard.txt" --data_path data/gsm8k/test.jsonl --icl_path samples/plans_code_traces/gsm8k/gpt-4-turbo_output.json --data_name "gsm8k" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 6
# python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_conf.yaml --api_key "8Qm1rHhRD57Orx4pkbKXT1k1RheU9UPyidVKECLU" --prompt_dir "prompts/gsm8k/standard.txt" --data_path data/gsm8k/test.jsonl --icl_path samples/plans_code_traces/gsm8k/gpt-4-turbo_output.json --data_name "gsm8k" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 6
# python llmsearch/run_gpt.py --model_config_path llmsearch/models/gpt3_5_conf.yaml --api_key "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" --prompt_dir "prompts/gsm8k/standard.txt" --data_path data/gsm8k/test.jsonl --icl_path samples/plans_code_traces/gsm8k/gpt-4-turbo_output.json --data_name "gsm8k" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 6
python llmsearch/run_gpt.py --model_config_path llmsearch/models/mixtral.yaml --api_key "a14bb51e9bdd4ebf80b9fa061d26202c18ede18fcd2390a203486c15dfc03001" --prompt_dir "prompts/gsm8k/standard.txt" --data_path data/gsm8k/test.jsonl --icl_path samples/plans_code_traces/gsm8k/gpt-4-turbo_output.json --data_name "gsm8k" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 6

# python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_plus_conf.yaml --api_key "8Qm1rHhRD57Orx4pkbKXT1k1RheU9UPyidVKECLU" --prompt_dir "prompts/gsm8k/standard.txt" --data_path data/gsm8k/test.jsonl --icl_path samples/plans_code_traces/gsm8k/gpt-4-turbo_output.json --data_name "gsm8k" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 4
# python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_conf.yaml --api_key "8Qm1rHhRD57Orx4pkbKXT1k1RheU9UPyidVKECLU" --prompt_dir "prompts/gsm8k/standard.txt" --data_path data/gsm8k/test.jsonl --icl_path samples/plans_code_traces/gsm8k/gpt-4-turbo_output.json --data_name "gsm8k" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 4
# python llmsearch/run_gpt.py --model_config_path llmsearch/models/gpt3_5_conf.yaml --api_key "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" --prompt_dir "prompts/gsm8k/standard.txt" --data_path data/gsm8k/test.jsonl --icl_path samples/plans_code_traces/gsm8k/gpt-4-turbo_output.json --data_name "gsm8k" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 4
python llmsearch/run_gpt.py --model_config_path llmsearch/models/mixtral.yaml --api_key "a14bb51e9bdd4ebf80b9fa061d26202c18ede18fcd2390a203486c15dfc03001" --prompt_dir "prompts/gsm8k/standard.txt" --data_path data/gsm8k/test.jsonl --icl_path samples/plans_code_traces/gsm8k/gpt-4-turbo_output.json --data_name "gsm8k" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 4
python llmsearch/run_gpt.py --model_config_path llmsearch/models/llama3_conf.yaml --api_key "a14bb51e9bdd4ebf80b9fa061d26202c18ede18fcd2390a203486c15dfc03001" --prompt_dir "prompts/gsm8k/standard.txt" --data_path data/gsm8k/test.jsonl --icl_path samples/plans_code_traces/gsm8k/gpt-4-turbo_output.json --data_name "gsm8k" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 2

# python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_plus_conf.yaml --api_key "8Qm1rHhRD57Orx4pkbKXT1k1RheU9UPyidVKECLU" --prompt_dir "prompts/gsm8k/standard.txt" --data_path data/gsm8k/test.jsonl --icl_path samples/plans_code_traces/gsm8k/gpt-4-turbo_output.json --data_name "gsm8k" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 2
# python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_conf.yaml --api_key "8Qm1rHhRD57Orx4pkbKXT1k1RheU9UPyidVKECLU" --prompt_dir "prompts/gsm8k/standard.txt" --data_path data/gsm8k/test.jsonl --icl_path samples/plans_code_traces/gsm8k/gpt-4-turbo_output.json --data_name "gsm8k" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 2
# python llmsearch/run_gpt.py --model_config_path llmsearch/models/gpt3_5_conf.yaml --api_key "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" --prompt_dir "prompts/gsm8k/standard.txt" --data_path data/gsm8k/test.jsonl --icl_path samples/plans_code_traces/gsm8k/gpt-4-turbo_output.json --data_name "gsm8k" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 2
python llmsearch/run_gpt.py --model_config_path llmsearch/models/mixtral.yaml --api_key "a14bb51e9bdd4ebf80b9fa061d26202c18ede18fcd2390a203486c15dfc03001" --prompt_dir "prompts/gsm8k/standard.txt" --data_path data/gsm8k/test.jsonl --icl_path samples/plans_code_traces/gsm8k/gpt-4-turbo_output.json --data_name "gsm8k" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 2
python llmsearch/run_gpt.py --model_config_path llmsearch/models/llama3_conf.yaml --api_key "a14bb51e9bdd4ebf80b9fa061d26202c18ede18fcd2390a203486c15dfc03001" --prompt_dir "prompts/gsm8k/standard.txt" --data_path data/gsm8k/test.jsonl --icl_path samples/plans_code_traces/gsm8k/gpt-4-turbo_output.json --data_name "gsm8k" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 1
