python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_plus_conf.yaml --api_key "8Qm1rHhRD57Orx4pkbKXT1k1RheU9UPyidVKECLU" --prompt_dir "prompts/clutrr/standard.txt" --data_path data/clutrr/test.jsonl --icl_path samples/plans_code_traces/clutrr/gpt-4-turbo_output.json --data_name "clutrr" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 8
python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_conf.yaml --api_key "8Qm1rHhRD57Orx4pkbKXT1k1RheU9UPyidVKECLU" --prompt_dir "prompts/clutrr/standard.txt" --data_path data/clutrr/test.jsonl --icl_path samples/plans_code_traces/clutrr/gpt-4-turbo_output.json --data_name "clutrr" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 8
python llmsearch/run_gpt.py --model_config_path llmsearch/models/gpt3_5_conf.yaml --api_key "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" --prompt_dir "prompts/clutrr/standard.txt" --data_path data/clutrr/test.jsonl --icl_path samples/plans_code_traces/clutrr/gpt-4-turbo_output.json --data_name "clutrr" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 8

python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_plus_conf.yaml --api_key "8Qm1rHhRD57Orx4pkbKXT1k1RheU9UPyidVKECLU" --prompt_dir "prompts/clutrr/standard.txt" --data_path data/clutrr/test.jsonl --icl_path samples/plans_code_traces/clutrr/gpt-4-turbo_output.json --data_name "clutrr" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 6
python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_conf.yaml --api_key "8Qm1rHhRD57Orx4pkbKXT1k1RheU9UPyidVKECLU" --prompt_dir "prompts/clutrr/standard.txt" --data_path data/clutrr/test.jsonl --icl_path samples/plans_code_traces/clutrr/gpt-4-turbo_output.json --data_name "clutrr" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 6
python llmsearch/run_gpt.py --model_config_path llmsearch/models/gpt3_5_conf.yaml --api_key "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" --prompt_dir "prompts/clutrr/standard.txt" --data_path data/clutrr/test.jsonl --icl_path samples/plans_code_traces/clutrr/gpt-4-turbo_output.json --data_name "clutrr" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 6

python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_plus_conf.yaml --api_key "8Qm1rHhRD57Orx4pkbKXT1k1RheU9UPyidVKECLU" --prompt_dir "prompts/clutrr/standard.txt" --data_path data/clutrr/test.jsonl --icl_path samples/plans_code_traces/clutrr/gpt-4-turbo_output.json --data_name "clutrr" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 4
python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_conf.yaml --api_key "8Qm1rHhRD57Orx4pkbKXT1k1RheU9UPyidVKECLU" --prompt_dir "prompts/clutrr/standard.txt" --data_path data/clutrr/test.jsonl --icl_path samples/plans_code_traces/clutrr/gpt-4-turbo_output.json --data_name "clutrr" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 4
python llmsearch/run_gpt.py --model_config_path llmsearch/models/gpt3_5_conf.yaml --api_key "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" --prompt_dir "prompts/clutrr/standard.txt" --data_path data/clutrr/test.jsonl --icl_path samples/plans_code_traces/clutrr/gpt-4-turbo_output.json --data_name "clutrr" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 4

python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_plus_conf.yaml --api_key "8Qm1rHhRD57Orx4pkbKXT1k1RheU9UPyidVKECLU" --prompt_dir "prompts/clutrr/standard.txt" --data_path data/clutrr/test.jsonl --icl_path samples/plans_code_traces/clutrr/gpt-4-turbo_output.json --data_name "clutrr" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 2
python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_conf.yaml --api_key "8Qm1rHhRD57Orx4pkbKXT1k1RheU9UPyidVKECLU" --prompt_dir "prompts/clutrr/standard.txt" --data_path data/clutrr/test.jsonl --icl_path samples/plans_code_traces/clutrr/gpt-4-turbo_output.json --data_name "clutrr" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 2
python llmsearch/run_gpt.py --model_config_path llmsearch/models/gpt3_5_conf.yaml --api_key "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" --prompt_dir "prompts/clutrr/standard.txt" --data_path data/clutrr/test.jsonl --icl_path samples/plans_code_traces/clutrr/gpt-4-turbo_output.json --data_name "clutrr" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 2 