python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_plus_conf.yaml --api_key "ItN5fkCoSEc88La1OQSAMX8cN3RWL7W7SA6sL157" --prompt_dir "prompts/date/standard.txt" --data_path data/date/test.jsonl --icl_path samples/plans_code_traces/date/gpt-4-turbo_output.json --data_name "date" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 9
python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_conf.yaml --api_key "ItN5fkCoSEc88La1OQSAMX8cN3RWL7W7SA6sL157" --prompt_dir "prompts/date/standard.txt" --data_path data/date/test.jsonl --icl_path samples/plans_code_traces/date/gpt-4-turbo_output.json --data_name "date" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 9
python llmsearch/run_gpt.py --model_config_path llmsearch/models/gpt3_5_conf.yaml --api_key "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" --prompt_dir "prompts/date/standard.txt" --data_path data/date/test.jsonl --icl_path samples/plans_code_traces/date/gpt-4-turbo_output.json --data_name "date" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 9
python llmsearch/run_gpt.py --model_config_path llmsearch/models/llama3-1_conf.yaml --api_key "a14bb51e9bdd4ebf80b9fa061d26202c18ede18fcd2390a203486c15dfc03001" --prompt_dir "prompts/date/standard.txt" --data_path data/date/test.jsonl --icl_path samples/plans_code_traces/date/gpt-4-turbo_output.json --data_name "date" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 9

python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_plus_conf.yaml --api_key "ItN5fkCoSEc88La1OQSAMX8cN3RWL7W7SA6sL157" --prompt_dir "prompts/date/standard.txt" --data_path data/date/test.jsonl --icl_path samples/plans_code_traces/date/gpt-4-turbo_output.json --data_name "date" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 8
python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_conf.yaml --api_key "ItN5fkCoSEc88La1OQSAMX8cN3RWL7W7SA6sL157" --prompt_dir "prompts/date/standard.txt" --data_path data/date/test.jsonl --icl_path samples/plans_code_traces/date/gpt-4-turbo_output.json --data_name "date" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 8
python llmsearch/run_gpt.py --model_config_path llmsearch/models/gpt3_5_conf.yaml --api_key "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" --prompt_dir "prompts/date/standard.txt" --data_path data/date/test.jsonl --icl_path samples/plans_code_traces/date/gpt-4-turbo_output.json --data_name "date" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 8

python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_plus_conf.yaml --api_key "ItN5fkCoSEc88La1OQSAMX8cN3RWL7W7SA6sL157" --prompt_dir "prompts/date/standard.txt" --data_path data/date/test.jsonl --icl_path samples/plans_code_traces/date/gpt-4-turbo_output.json --data_name "date" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 6
python llmsearch/run_gpt.py --model_config_path llmsearch/models/command_r_conf.yaml --api_key "ItN5fkCoSEc88La1OQSAMX8cN3RWL7W7SA6sL157" --prompt_dir "prompts/date/standard.txt" --data_path data/date/test.jsonl --icl_path samples/plans_code_traces/date/gpt-4-turbo_output.json --data_name "date" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 6
python llmsearch/run_gpt.py --model_config_path llmsearch/models/gpt3_5_conf.yaml --api_key "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" --prompt_dir "prompts/date/standard.txt" --data_path data/date/test.jsonl --icl_path samples/plans_code_traces/date/gpt-4-turbo_output.json --data_name "date" --output_dir samples/final_predictions --execute_mode "trace" --num_samples 6


